@startuml

!define SCSPRITES https://github.com/jballe/plantuml-sitecore-icons/blob/master/img/sc10-cloud-archictecture
!define XMLOGO <img:SCSPRITES/xm-cloud-64.png?raw=true>
!define XPLOGO <img:SCSPRITES/xp-64.png?raw=true>
!define SEARCHLOGO <img:SCSPRITES/search-64.png?raw=true>
!define SENDLOGO <img:SCSPRITES/send-64.png?raw=true>
!define OPENAILOGO <img:https://dwglogo.com/wp-content/uploads/2019/03/1600px-OpenAI_logo-100x70.png>
!define SLACKLOGO <img:https://images.squarespace-cdn.com/content/v1/62460a56418af8236d4f3fee/129e20df-c522-48f8-a530-a276da302a7e/Stormboard%2Band%2BSlack.png?format=100w{scale=0.7}>
!define RSSICON <img:https://icons.iconarchive.com/icons/paomedia/small-n-flat/256/rss-icon.png{scale=0.2}>

together {
    rectangle "Sitecore XM/XP\nXPLOGO" as xm
    rectangle "XM Cloud\nXMLOGO" as xmc
    rectangle "Sitecore Send\nSENDLOGO" as send
    rectangle "Sitecore Search\nSEARCHLOGO" as search
}
rectangle "Slack\nSLACKLOGO" as slack
file "RSS feed\nRSSICON" as rss
rectangle "Open AI\nOPENAILOGO" as ai

frame "NewsMixer" {
    frame "Input sources" as sources <<layer>> {
        component "GraphQL Endpoint\nInput Source"   as sc_source
        component "Sitecore Search \nInput Source"  as search_source
        component "Slack \nInput Source"     as slack_source<<proposal>>
        sc_source -.up-> xm
        sc_source -.up-> xmc
        search_source -.up-> search
        slack_source -.up-> slack
    }
    frame "Transforms pipeline" as transform <<layer>> {
        component "OpenAI Transform" as ai_transform
        ai_transform -right.-> ai : Article summary, style, translation
        'component "OpenAI Translate" as ai_translate
        'ai_translate -right.-> ai : Translate title
    }

    frame "Output types" as output <<layer>> {
        component "Dev Console \nOutput" as dev_output
        component "RSS File \nOutput"  as rss_output
    }

    'sc_source --> transform
    rss_output -.-> rss

    sources --> transform
    transform --> output
}

send -down.-.-.-> rss

hide stereotype
skinparam frame<<layer>> {
    BorderStyle dashed
    RoundCorner 20
}

skinparam {
    RectangleBackgroundColor white
    RectangleBorderThickness 2px
    RectangleFontStyle Bold
    FileBackgroundColor white
    FileBorderThickness 2px
    FileFontStyle Bold
}

skinparam component {
    BackgroundColor LightGreen
} 

skinparam component<<proposal>> {
    BackgroundColor lightblue
    FontColor grey
}


@enduml