@startuml

!define SCSPRITES https://github.com/jballe/plantuml-sitecore-icons/blob/master/img/sc10-cloud-archictecture
!define XMLOGO <img:SCSPRITES/xm-cloud-64.png?raw=true>
!define XPLOGO <img:SCSPRITES/xp-64.png?raw=true>
!define SEARCHLOGO <img:SCSPRITES/search-64.png?raw=true>
!define SENDLOGO <img:SCSPRITES/send-64.png?raw=true>
!define OPENAILOGO <img:https://dwglogo.com/wp-content/uploads/2019/03/1600px-OpenAI_logo-100x70.png>
!define SLACKLOGO <img:https://previews.us-east-1.widencdn.net/preview/48045879/assets/asset-view/0cece34e-cbb7-4c6f-be3e-d475baeb3a8d/thumbnail/eyJ3Ijo0ODAsImgiOjQ4MCwic2NvcGUiOiJhcHAifQ==?Expires=1709413200&Signature=Jy1lQNwOy~JBeLKvMIiuRmGIJDbLN6-soHQRCku2MX5O6pz9S6V92J-xr-TImumb5MblriL9tRwBkq4MrvtZ9-fin8s3ELEFjS1NxSd21DOd8lE-FOFZxb87glxII9qRnrFo7vDBPm71x925s9j7r~7sejfVi9uFEAOwfZJ4yeNNUOrFr~OuafUlXfmV1DOiaFObmW~vdmalfNTt6chnimdGQIsUuWjgta336~tLJz~5CLOZBtkdamfRJk1S9lusfw8znYW~3zx9voBXRwEOnIkRdBLIfUbe89G9ZXGbZ7lRgJAuHknA1SiC07sMrP~hsUEP4kXN8QFnE2zrrCg6fQ__&Key-Pair-Id=APKAJM7FVRD2EPOYUXBQ{scale=0.25}>

together {
    rectangle "Sitecore XM/XP\nXPLOGO" as xm
    rectangle "XM Cloud\nXMLOGO" as xmc
    rectangle "Sitecore Send\nSENDLOGO" as send
    rectangle "Sitecore Search\nSEARCHLOGO" as search
}
rectangle "Slack\nSLACKLOGO" as slack
file "RSS feed" as rss
rectangle "Open AI\nOPENAILOGO" as ai

frame "NewsMixer" {
    frame "Input sources" as sources <<layer>> {
        component "GraphQL Endpoint\nInput Source"   as sc_source
        component "Sitecore Search \nInput Source"  as search_source<<proposal>>
        component "Slack \nInput Source"     as slack_source<<proposal>>
        sc_source -.up-> xm
        sc_source -.up-> xmc
        search_source -.up-> search
        slack_source -.up-> slack
    }
    frame "Transforms pipeline" as transform <<layer>> {
        component "OpenAI Transform" as ai_transform
        ai_transform -right.-> ai : Article summary, style, translation
    }

    frame "Output types" as output <<layer>> {
        component "Dev Console \nOutput" as dev_output
        component "RSS File \nOutput"  as rss_output
    }

    'sc_source --> transform
    rss_output -.-> rss

    sources --> transform
    transform --> output
}

send -down.-.-.-> rss

hide stereotype
skinparam frame<<layer>> {
    BorderStyle dashed
    RoundCorner 20
}

skinparam rectangle {
    BackgroundColor white
    BorderThickness 2px
    FontStyle Bold
}

skinparam component {
    BackgroundColor LightGreen
} 

skinparam component<<proposal>> {
    BackgroundColor lightblue
    FontColor grey
}


@enduml